library(shiny)
library(ckanr)
library(shinyjs)
library(dplyr)
library(forcats)
library(ggplot2)
library(scales)
library(sf)
library(naomi)
library(lemon)
library(stringr)
library(jsonlite)
library(httr)
library(hintr)
library(lubridate)
library(shinycssloaders)
library(shinyWidgets)
library(tidyr)
library(rmarkdown)
library(knitr)
library(tinytex)

shinyOptions(shiny.sanitize.errors = FALSE)

source("src/package_choice_functions.R")
source("src/validation_functions.R")

source("src/server/introduction_server.R")
source("src/server/viewer_server.R")
source("src/server/download_server.R")

source("src/ui/navigation.R")
source("src/ui/introduction.R")
source("src/ui/viewer.R")

shiny::shinyAppDir("src")